server.port=8082
spring.profiles.active=dev
management.endpoints.web.exposure.include=info

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation= true
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto= update
# Enable logging of SQL statements
spring.jpa.show-sql=true
# Pretty print the SQL statements
spring.jpa.properties.hibernate.format_sql=true
# Log the SQL parameters
spring.jpa.properties.hibernate.type=trace
# Set the logging level to DEBUG for the SQL logger
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Enable Hibernate second-level cache statistics
spring.jpa.properties.hibernate.generate_statistics=true

# Log cache hits, misses, and puts
#logging.level.org.hibernate.cache=DEBUG
#logging.level.org.ehcache=DEBUG


# App Properties
bezkoder.app.jwtSecret= ======================BezKoder=Spring===========================
bezkoder.app.jwtExpirationMs=86400000


logging.file.name=logs/application.log
logging.level.org.springframework=INFO

# Log pattern format (optional)
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n

# Log levels (optional, to set specific levels for different packages)

#logging.level.org.springframework=DEBUG
#logging.level.com.yourpackage=DEB
