server.port=8082
spring.profiles.active=dev
management.endpoints.web.exposure.include=info

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation= true
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto= update


# App Properties
bezkoder.app.jwtSecret= ======================Tax Management ===========================
bezkoder.app.jwtExpirationMs= 86400000


logging.file.name=logs/application.log
logging.level.org.springframework=INFO

# Log pattern format (optional)
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n

# Log levels (optional, to set specific levels for different packages)

#logging.level.org.springframework=DEBUG
#logging.level.com.yourpackage=DEB
